name: star_dev

services:
  star_dev:
    build:
      context: .
      dockerfile: ./Dockerfile.star_uv
    image: star-dev:latest
    container_name: star_dev_container
    privileged: true
    network_mode: host
    tty: true
    stdin_open: true
    runtime: nvidia

    gpus: all

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

      - HF_HOME=/cache/huggingface
      - HUGGINGFACE_HUB_CACHE=/cache/huggingface/hub
      - TRANSFORMERS_CACHE=/cache/huggingface/transformers
      - HF_DATASETS_CACHE=/cache/huggingface/datasets
      - TORCH_HOME=/cache/torch
      - XDG_CACHE_HOME=/cache

      - VIRTUAL_ENV=/bootstrap/.venv
      - PATH=/bootstrap/.venv/bin:${PATH}
      - PYTHONPATH=/workspace/star/src:${PYTHONPATH}
    # ===============================
    # Volume Mounts
    # ===============================
    volumes:
      # ---- Project Source Code ----
      - ..:/workspace/star
      # ---- Dataset ----
      - /media/ssd/Local_data/:/workspace/Local_data
      # ----Model Checkpoints (Critical for Large Models) ----
      - /media/ssd/weights/:/workspace/star/weights
      - ../data/:/workspace/data
      - ../data/coda/:/workspace/coda
      # ---- Output / Results ----
      - ../results:/workspace/results
      # ---- Pre-downloaded Model Weights (Static Files) ----
      # - ./third_parties:/workspace/third_parties
      # ---- Shared HuggingFace & Torch Cache (Critical) ----
      - $HOME/.cache/huggingface:/cache/huggingface
      - $HOME/.cache/torch:/cache/torch
      # ---- X11 Forwarding ----
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    working_dir: /workspace